export default [
  'strapi::logger',
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::query',
  "global::raw-body",
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
  "global::rate-limit",
  "global::ip-rate-limit",
];
