name: Build and Deploy

on:
    push:
        branches:
            - main
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                ports: ["5432:5432"]
                env:
                    POSTGRES_USER: strapi
                    POSTGRES_PASSWORD: strapi
                    POSTGRES_DB: strapi
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install backend dependencies (Strapi)
              working-directory: ./backend
              run: npm ci

            - name: Build Strapi
              working-directory: ./backend
              run: npm run build

            - name: Start Strapi in background
              working-directory: ./backend
              env:
                  # these are random symbols :D
                  APP_KEYS: t*vz2>x&/+(H^<rR9PqG?h,B&UaZ+:Q2bD`)]Y;8nR}mH,nws+!c:E3h]5XtjD$.Ga})
                  API_TOKEN_SALT: w;Sc5ytAP7CVFM`-q'W4Y%
                  ADMIN_JWT_SECRET: f+#UErT7~d-4px(:vA;e?z
                  TRANSFER_TOKEN_SALT: V;Aj'!eqY^?duz_ZF76x29
                  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
              run: |
                  nohup npm run start &

            - name: Wait for Strapi to start
              run: |
                  echo "Waiting for Strapi..."
                  until curl -s -o /dev/null http://127.0.0.1:1337/admin; do
                      sleep 1
                      echo "Still waiting..."
                  done
                  echo "Strapi is up!"

            - name: Install frontend dependencies (Next.js)
              working-directory: ./frontend
              run: npm ci

            - name: Build frontend
              working-directory: ./frontend
              env:
                  NEXT_PUBLIC_DB_URL: http://127.0.0.1:1337
                  NEXT_PUBLIC_STRAPI_URL: http://127.0.0.1:1337
              run: npm run build
